name: Check PTT New Posts

permissions:
  contents: write

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run crawler
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          NORD_USER: ${{ secrets.NORD_USER }}
          NORD_PASS: ${{ secrets.NORD_PASS }}
        run: python main.py

      - name: Commit & push sent.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add sent.json
          git diff --cached --quiet || git commit -m "chore: update sent list $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          git push
